version: "3.9"
services:
  api:
    build:
      context: ./
    image: splitdecision
    environment:
      SD_DB_HOST: postgres
      SD_DB_USER: sd_appuser
      SD_DB_PASSWORD: splitd
    ports:
      - 9002:9001

  postgres:
    image: postgres:13.4
    environment:
      POSTGRES_DB: splitdecision
      POSTGRES_USER: root
      POSTGRES_PASSWORD: splitd
    ports:
      - 5432:5432
    volumes:
      - ~/.docker-volumes/splitdecision:/var/lib/postgresql/data

  migrate:
    depends_on:
      - postgres
    image: amacneil/dbmate:latest
    environment:
      DATABASE_URL: postgres://root:sd_appuser@postgres:5432/splitdecision?sslmode=disable
    volumes:
      - "./migrations:/opt/app/migrations"
    command: "-d /opt/app/migrations up"
